{{- if .Values.corerpc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-rpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neon-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.corerpc.hpa.enabled }}
  replicas: {{ .Values.corerpc.replicas }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      application-pod: neon-core-rpc
      {{- include "neon-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubernetes.io/psp: restricted
        checksum/secret: {{ include (print $.Template.BasePath "/core-rpc-config.yaml") . | sha256sum }}  
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{ .Release.Namespace }}
        vault.hashicorp.com/agent-inject-secret-proxy-env: {{ .Release.Namespace }}/data/proxy_env
        vault.hashicorp.com/agent-inject-template-proxy-env: |
          {{`{{- with secret "`}}{{.Release.Namespace }}{{`/data/proxy_env" -}}
            {{ range $k, $v := .Data.data }}
            export  {{ $k }}={{ $v }}
            {{ end }}
          {{- end }}`}} 
        vault.hashicorp.com/agent-inject-secret-core-rpc-env: {{ .Release.Namespace }}/data/core_rpc_env
        vault.hashicorp.com/agent-inject-template-core-rpc-env: |
          {{`{{- with secret "`}}{{.Release.Namespace }}{{`/data/core_rpc_env" -}}
            {{ range $k, $v := .Data.data }}
            export  {{ $k }}={{ $v }}
            {{ end }}
          {{- end }}`}}
      labels:
        application-pod: neon-core-rpc
        {{- include "neon-proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: neon-core-rpc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.corerpc.image.repository }}:{{ .Values.corerpc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: {{ .Values.corerpc.logVerbosity | default "warn" | quote }}
            - name: COMMITMENT
              value: {{ .Values.corerpc.COMMITMENT | default "processed" | quote }}
            - name: TRACER_DB_TYPE
              value: {{ .Values.corerpc.tracer_db.type }}
            - name: NEON_DB_CLICKHOUSE_URLS
              value: {{ .Values.corerpc.tracer_db.clickhouse_urls }}
            - name: SOLANA_TEST_ACCOUNTS_INDEX_MEMORY_LIMIT_MB
              value: "value"
            - name: SOLANA_RAYON_THREADS
              value: "1"
          envFrom:
          - secretRef: 
              name: core-rpc-config
        {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}
          {{- if .Values.corerpc.resources }}
          resources:
            {{- toYaml .Values.corerpc.resources | nindent 12 }}          
          {{- else if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          command: ["/bin/bash", "-c"]
          args: ["/opt/neon-proxy/core-rpc/run-core-rpc.sh"]
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
