{{- if or (.Values.indexer.enabled) (eq (.Values.indexer.enabled | toString) "") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neon-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      application-pod: neon-proxy-indexer
      {{- include "neon-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubernetes.io/psp: restricted
        checksum/secret: {{ include (print $.Template.BasePath "/proxy-config.yaml") . | sha256sum }}  
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{ .Release.Namespace }}
        vault.hashicorp.com/agent-inject-secret-proxy-env: {{ .Release.Namespace }}/data/proxy_env
        vault.hashicorp.com/agent-inject-template-proxy-env: |
          {{`{{- with secret "`}}{{.Release.Namespace }}{{`/data/proxy_env" -}}
            {{ range $k, $v := .Data.data }}
            export  {{ $k }}={{ $v }}
            {{ end }}
          {{- end }}`}}  
        vault.hashicorp.com/agent-inject-secret-indexer-env: {{ .Release.Namespace }}/data/indexer_env
        vault.hashicorp.com/agent-inject-template-indexer-env: |
          {{`{{- with secret "`}}{{.Release.Namespace }}{{`/data/indexer_env" -}}
            {{ range $k, $v := .Data.data }}
            export  {{ $k }}={{ $v }}
            {{ end }}
          {{- end }}`}}       
      labels:
        application-pod: neon-proxy-indexer
        {{- include "neon-proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: INDEXER_KEY
            value: {{ .Values.indexer.indexerKey | toString | quote }}
        {{- if .Values.envFrom }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
        {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}  
          workingDir: /opt/neon-proxy
          {{- if and .Values.indexer.resources.requests.cpu .Values.indexer.resources.requests.memory  }}
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}          
          {{- else if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          command: ["/bin/bash"]
          args: ["indexer/run-indexer.sh"]
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
