apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SOLANA_URL: {{ .Values.solanaUrl | b64enc | quote }}
  SOLANA_WS_URL: {{ .Values.solanaWsUrl | b64enc | quote }}
  NEON_EVM_PROGRAM: {{ .Values.neon_evm_program | b64enc | quote }}
  PP_SOLANA_URL: {{ .Values.ppsolanaUrl | b64enc | quote }}
  MINIMAL_GAS_PRICE: {{ .Values.minimal_gas_price | toString | b64enc | quote }}
  PROXY_COUNT: {{ .Values.proxyCount | toString | b64enc | quote }}
  KEYS_PER_PROXY: {{ .Values.keysPerProxy | toString | b64enc | quote }}