#https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

persistence:
  enabled: true

dashboardProviders: 
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.{{ .Values.namespace }}.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki.{{ .Values.namespace }}.svc.cluster.local:3100
      access: proxy
      isDefault: false


dashboards:
  default:
    loki-app:
      gnetId: 13639
      datasource: Loki
    prometheus-k8s:
      gnetId: 1860
      datasource: Prometheus
    prometheus-k8s2:
      gnetId: 12117
      datasource: Prometheus
    neon-proxy-1:
      gnetId: 17591
      datasource: Prometheus
    neon-proxy-indexer:
      gnetId: 17592
      datasource: Prometheus

ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /grafana
  pathType: Prefix
  hosts:
    - chart-example.local
  extraPaths: []
  tls: []