apiVersion: v1
kind: Secret
metadata:
  name: loki-stack
  namespace: neon-proxy
type: Opaque
stringData:
  loki.yaml: |
    auth_enabled: false
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
      working_directory: /data/loki/retention
      compaction_interval: 1h
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    server:
      http_listen_port: 3100
      grpc_server_max_recv_msg_size: 204857600
      grpc_server_max_send_msg_size: 204857600
    frontend:
      grpc_client_config:
        max_recv_msg_size: 204857600
        max_send_msg_size: 204857600
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 204857600
        max_send_msg_size: 204857600
    frontend_worker:
      grpc_client_config:
        max_recv_msg_size: 204857600
        max_send_msg_size: 204857600
    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /data/loki
    schema_config:
      configs:
      - from: 2020-05-15
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
    storage_config:
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      split_queries_by_interval: 30m
      max_query_parallelism: 64
      max_entries_limit_per_query: 900000000
      max_line_size: 0
      retention_period: 2w
    query_range:
      align_queries_with_step: true
      max_retries: 10
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100
            ttl: 24h