apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  neon-db.sql: {{ tpl (.Files.Get "files/neon-db.sql") . | quote }}
  vault.sql: {{ tpl (.Files.Get "files/vault.sql") . | quote }}
{{- if .Values.upgrade_14_to_15.enabled }}
  upgrade_postgres_db_14_to_15.sh: {{ tpl (.Files.Get "files/upgrade_postgres_db_14_to_15.sh") . | quote }}
{{- end }}