groups:
  - name: neon_indexer
    rules:
      - alert: indexer stopped parsing blocks
        annotations:
          summary: indexer stopped parsing blocks
          description: indexer stopped parsing blocks
        expr: (block_parsed{reindex=""} - (block_parsed{reindex=""} offset 2m)) == 0
        for: 10s
        labels:
          severity: critical
      - alert: indexer can't get block from solana
        annotations:
          summary: indexer can't get block from solana
          description: indexer can't get block from solana
        expr: (block_confirmed - (block_confirmed offset 2m)) == 0
        for: 10s
        labels:
          severity: critical

  - name: neon_proxy
    rules:
      - alert: operator key balance less than 2
        annotations:
          summary: operator key balance less than 2
          description: operator key balance less than 2
        expr: operator_sol_balance < 2
        for: 5s
        labels:
          severity: warning
      - alert: operator key balance less than 1
        annotations:
          summary: operator key balance less than 1
          description: operator key balance less than 1
        expr: operator_sol_balance < 1
        for: 5s
        labels:
          severity: critical
      - alert: operator_resource_disabled_count
        annotations:
          summary: operator_resource_disabled_count
          description: operator_resource_disabled_count
        expr: operator_resource_disabled_count > 2
        for: 5s
        labels:
          severity: warning
      - alert: db connection is lost
        annotations:
          summary: db connection is lost
          description: db connection is lost, gotta do something
        expr: db_health == 0
        for: 5s
        labels:
          severity: critical
      - alert: solana rpc connection is lost
        annotations:
          summary: solana rpc connection is lost
          description: solana rpc connection is lost, gotta do something
        expr: solana_rpc_health == 0
        for: 5s
        labels:
          severity: critical
      - alert: neon_tx_canceled
        annotations:
          summary: neon_tx_canceled
          description: there are canceled Neon transactions
        expr: tx_canceled > 0
        for: 5s
        labels:
          severity: warning
