global:
  enabled: true

clusterType: "localhost"
environment: ""

postgres:
  enabled: false
  host: ""
  dbName: ""
  user: ""
  password: ""
  ssl: "allow"

migrate:
  enabled: false

image:
  repository: "postgres"
  pullPolicy: "IfNotPresent"
  tag: "14.0"

service:
  name: dbport
  type: ClusterIP
  port: 5432
  targetPort: 5432
  protocol: TCP
  labels: {}


# extraPorts:
#   - name: 
#     containerPort: 
#     protocol: 

persistence:
  accessModes: ReadWriteOnce
  size: "50Gi"
  storageClass: ""

#
postgresql:
  maxConnections: 2000
#

env:
  - name: MAX_CONNECTIONS
    value: "1000"


POSTGRES_ADMIN_USER: "postgres"
POSTGRES_ADMIN_PASSWD: ""

envFrom:
  - secretRef: 
      name: postgres-secret

volumeMounts:
  - name: postgres-config
    mountPath: /var/lib/postgresql/init_scripts/neon-db.sql
    subPath: neon-db.sql
  - name: postgres-config
    mountPath: /var/lib/postgresql/init_scripts/vault.sql
    subPath: vault.sql
  - name: postgresdata
    mountPath: /var/lib/postgresql/data/

extendedConfiguration: |
        max_connections = 2000
